FROM openjdk:17-jdk-slim as build
MAINTAINER coralieperez
COPY target/BankApplication-0.0.1-SNAPSHOT.jar BankApplication-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "/BankApplication-0.0.1-SNAPSHOT.jar"]

