services:

  account:
    image: bankApp/account
    ports:
      - "8080:8080"
    networks:
      - bankapplication-networks
    mem_limit: 700m
    depends_on:
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  cards:
    image: bankApp/cards
    ports:
      - "9000:9000"
    networks:
      - bankapplication-networks
    mem_limit: 700m
    depends_on:
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: bankApp/loans
    ports:
      - "8090:8090"
    networks:
      - bankapplication-networks
    mem_limit: 700m
    depends_on:
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  configserver:
    image: bankApp/configserver
    ports:
      - "8071:8071"
    networks:
      - bankapplication-networks
    mem_limit: 700m

  eurekaserver:
    image: bankApp/eurekaserver
    ports:
      - "8070:8070"
    networks:
      - bankapplication-networks
    mem_limit: 700m
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s

    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/


networks:
  bankapplication-networks: